### ISSUE TITLE
dev:Ram insanly stimulated 

### ISSUE THREAD

**Issue by antiyro** [starkware-libs/papyrus#501]
**UX report :**

Memory actual usage for block synchronization is insane, around 2.3gb average.
1. Any idea what is causing this?
2. What are your final expectations for RAM usage for sync and after sync?

**Comment by ShahakShama** [comment]
Thanks for opening this issue, and apologies for the delay in response

The node utilizes a memory-mapped file as its storage medium. The allocated physical memory for the file mapping will not be evicted as long as the kernel does not experience memory pressure issues. Consequently, the node consumes a large amount of memory, utilizing all the available RAM.

One way to solve this issue is to limit the amount of available RAM that the node's process has. In the linked PR, we describe this issue in the README and recommend setting a container with limited memory if you have other applications on your machine
